---
language: php
sudo: required
env:
  global:
    - TEST_S3_LOCATION='s3://TRAVISACCESSPHPUNIT:wJalrXUtnFEMI%2FSECRET%2FTRAVISPHPUNIT@us-east-1/?endpoint=http%3A%2F%2F127.0.0.1%3A9999&use_path_style_endpoint=1'

services:
  - docker
  - redis-server
  - memcached

cache:
  bundler: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.ocular

php:
  - hhvm
  - 7.2
  - 7.1
  - 7.0
  - 5.6

before_install:
  - echo "memory_limit=2G" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - wget https://scrutinizer-ci.com/ocular.phar -O ~/.ocular/ocular.phar
  - echo "extension = memcached.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

install:
  - sudo apt-get install libxml2-utils
  - curl https://bootstrap.pypa.io/get-pip.py >> ~/get-pip.py
  - sudo python ~/get-pip.py
  - sudo pip install yamllint
  - composer global require "dealerdirect/qa-tools:*"
  - "docker run -p 9999:9999 --name minio --rm \
     -e 'MINIO_ACCESS_KEY=TRAVISACCESSPHPUNIT' \
     -e 'MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/TRAVISKEYPHPUNIT' \
     --detach minio/minio server /data"

script:
  - composer validate
  - composer install -o --prefer-dist --no-scripts
  - >
    find . -type f -name "*.json" -not -path "./vendor/*" -print0 |
    xargs -0 --no-run-if-empty -n1 ~/.composer/vendor/bin/jsonlint -c -q
  - >
    find . -type f -name "*.yml" -not -path "./vendor/*" -print0 |
    xargs -0 --no-run-if-empty -n1 yamllint
  - >
    find . -type f -name "*.xml" -not -path "./vendor/*" -print0 |
    xargs -0 --no-run-if-empty -n1 xmllint --noout --encode utf-8
  - ~/.composer/vendor/bin/parallel-lint ./src
  - ~/.composer/vendor/bin/phpcs -p -n ./src
  - ~/.composer/vendor/bin/security-checker -n security:check --end-point=http://security.sensiolabs.org/check_lock
  - php -dxdebug.coverage_enable=1 ./vendor/bin/phpunit

after_script:
  - php ~/.ocular/ocular.phar code-coverage:upload --format=php-clover coverage.xml -vvv
